# Generated by Django 3.0 on 2021-01-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dat_pub',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=350, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblog.Post')),
            ],
        ),
    ]
