# Generated by Django 3.0 on 2021-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_auto_20210123_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='blogpage/% Y, % m, % d'),
        ),
    ]
