# Generated by Django 3.0 on 2021-01-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0005_auto_20210128_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dat_pub',
            field=models.DateTimeField(null=True),
        ),
    ]
