# Generated by Django 3.0 on 2021-02-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0006_auto_20210128_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
